### ISSUE TITLE
It seems that faster_coco_eval 1.3.1 has something that must be fixed.

### ISSUE THREAD

**Issue by JongWan-Kim** [MiXaiLL76/faster_coco_eval#7]
first. faster_coco_eval/extra/curves.py in [https://github.com/MiXaiLL76/faster_coco_eval/blob/9b064a2e79a96d5d1b26c221d3b9b323d5d87d71/faster_coco_eval/extra/curves.py#L363](code) should be erased "=" 
f"The calculation may not be accurate. No intersection of classes. {**self.useCats=**}" --->  f"The calculation may not be accurate. No intersection of classes. {**self.useCats**}" 

The second. faster_coco_eval/core/cocoeval.py in 
[https://github.com/MiXaiLL76/faster_coco_eval/blob/9b064a2e79a96d5d1b26c221d3b9b323d5d87d71/faster_coco_eval/core/cocoeval.py#L577](code) should be erased "=" 
(f'{**iouType=**} not supported'  --> f'{**iouType**} not supported')

**Comment by MiXaiLL76** [comment]
Why should they be erased?

```python3
>>> import math
>>> 
>>> math.pi
3.141592653589793
>>> print(f"math.pi={math.pi}")
math.pi=3.141592653589793
>>> print(f"{math.pi=}")
math.pi=3.141592653589793
>>>
```

I want to have an understanding of the variable being output, so I use "="

**Comment by Mark-ZhouWX** [comment]
I am working with python3.7.2
I got an error when import faster_eval_coco,
![image](https://github.com/MiXaiLL76/faster_coco_eval/assets/65532315/9ed24cfc-d92c-425b-ac8f-05b2096dbf4d)

Add I reproduce the root cause when I try
>>> import math
>>> print(f"{math.pi=}")
  File "<fstring>", line 1
    (math.pi=)
            ^
SyntaxError: invalid syntax
>>> print(f"{math.pi}")
3.141592653589793

It seem python 3.7 does not support this kind of f-string  f"{math.pi=}", Do you have plan to fix this issue?
